services:
  - type: web
    name: flowise
    env: node
    plan: free
    buildCommand: |
      yarn
      yarn build
    startCommand: yarn start
    envVars:
      - key: PORT
        value: 3000
      - key: FLOWISE_USERNAME
        value: admin
      - key: FLOWISE_PASSWORD
        value: career123
      - key: NODE_ENV
        value: production
      - key: FLOWISE_CORS_ORIGINS
        value: "*"
      - key: FLOWISE_ENABLE_CORS
        value: "true"
